---
- name: Tomcat playbook
  hosts: tomcat      
  become: yes               
 # become_method: sudo       
 # remote_user: root         
  vars:
    tomcat_ver: 9.0.30
    ui_manager_user: manager                    
    ui_manager_pass: Str0ngManagerP@ssw3rd      
    ui_admin_username: admin                    
    ui_admin_pass: Str0ngAdminP@ssw3rd        

- name: Check to see if Tomcat is installed
  shell: "ps -ef|grep /usr/local/tomcat/" 
  register: tomcat_is_installed

  - name: This playbook will only be included when Tomcat is not installed
  include: tomcat-playbook.yml
  roles:
    - { role: tomcat, when: tomcat_is_installed.rc ! == 0 }

